package com.clinicos.billing.subscription.model;

public enum FeatureCode {
    PATIENT_MANAGEMENT,
    APPOINTMENTS,
    FOLLOW_UPS,
    BASIC_MEDICAL_RECORDS,
    BASIC_PRESCRIPTIONS,
    BASIC_BILLING,
    NOTIFICATIONS,
    BASIC_REPORTS,
    STAFF_MANAGEMENT,
    ADVANCED_MEDICAL_RECORDS,
    ADVANCED_PRESCRIPTIONS,
    LAB_MANAGEMENT,
    PHARMACY,
    INVENTORY,
    ADVANCED_BILLING,
    ADVANCED_REPORTS,
    ANALYTICS,
    WHATSAPP,
    FILE_MANAGEMENT,
    AUDIT_HISTORY,
    MULTIPLE_LOCATIONS,
    ADVANCED_ANALYTICS,
    TELEMEDICINE,
    API_INTEGRATIONS,
    ADVANCED_STAFF_MANAGEMENT
}

