package com.clinicos.billing.subscription.model;

public enum SubscriptionAction {
    SUBSCRIPTION_CREATED,
    PLAN_CHANGED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_RENEWED,
    TRIAL_EXTENDED,
    CLINIC_SUSPENDED,
    CLINIC_REACTIVATED,
    FEATURE_OVERRIDE_CHANGED,
    ROLE_CHANGED,
    PERMISSION_CHANGED,
    ADDON_ACTIVATED,
    ADDON_DEACTIVATED
}

